language: cpp

before_script:
- if [ "$TRAVIS_BRANCH" == "master" ]; then travis_terminate 0; fi
- sudo apt-get install libboost-test-dev -y
- echo "deb http://archive.ubuntu.com/ubuntu xenial main universe" | sudo tee -a /etc/apt/sources.list
- sudo apt-get update -qq

stages:
  - name: Build
  - name: Test
  - name: Deploy

jobs:
  include:
    - stage: "Build"
      name: "build"
      script:
        - cd $TRAVIS_BRANCH
        - cmake .
        - cmake --build .
        - cmake --build . --target package
    - stage: "Test"
      name: "unit tests"
      script:
        - cd $TRAVIS_BRANCH
        - cmake .
        - cmake --build . --target test
        - ./test
    - stage: "Deploy"
      name: "deploy"
      script:
        - cd $TRAVIS_BRANCH
        - cmake .
        - cmake --build . --target package
      deploy:
        provider: bintray
        file: $TRAVIS_BRANCH-0.0.$TRAVIS_BUILD_NUMBER-Linux.deb
        user: f0m41h4u7
        key: $BINTRAY_API_KEY
        skip_cleanup: true
        on:
          all_branches: true
