language: cpp

install:
- if [ "$TRAVIS_BRANCH" == "master" ]; then travis_terminate 0; fi

stages:
  - name: Test
  - name: Deploy

jobs:
  include:
    - stage: "Test"
      name: "unit tests"
      script:
        - docker build -t cpp --build-arg PROJECT=$TRAVIS_BRANCH .
        - docker run -e TRAVIS_BUILD_NUMBER=$TRAVIS_BUILD_NUMBER -e TRAVIS_BRANCH=$TRAVIS_BRANCH -e BINTRAY_API_KEY=$BINTRAY_API_KEY cpp test
      if: |
        (type = push)
    - stage: "Deploy"
      name: "deploy"
      script:
        - docker run -e TRAVIS_BUILD_NUMBER=$TRAVIS_BUILD_NUMBER -e TRAVIS_BRANCH=$TRAVIS_BRANCH -e BINTRAY_API_KEY=$BINTRAY_API_KEY cpp deb
      if: |
        (type = push)
