language: cpp
compiler: gcc
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-9
      - g++-9
      - libboost-test-dev

install:
- if [ "$TRAVIS_BRANCH" == "master" ]; then travis_terminate 0; fi
- echo "deb http://archive.ubuntu.com/ubuntu xenial main universe" | sudo tee -a /etc/apt/sources.list
- sudo apt-get update -qq
- sudo ln -s /usr/bin/gcc-9 /usr/local/bin/gcc
- sudo ln -s /usr/bin/g++-9 /usr/local/bin/g++
- export CC=/usr/bin/gcc-9
- export CXX=/usr/bin/g++-9

stages:
  - name: Test
  - name: Deploy

jobs:
  include:
    - stage: "Test"
      name: "unit tests"
      script:
        - cd $TRAVIS_BRANCH
        - cmake .
        - make test
        - ./test
    - stage: "Deploy"
      name: "deploy"
      script:
        - cd $TRAVIS_BRANCH
        - cmake .
        - cmake --build .
        - cmake --build . --target package
      deploy:
        provider: bintray
        file: $TRAVIS_BRANCH-0.0.$TRAVIS_BUILD_NUMBER-Linux.deb
        user: f0m41h4u7
        key: $BINTRAY_API_KEY
        skip_cleanup: true
        on:
          all_branches: true
