language: cpp

install:
- if [ "$TRAVIS_BRANCH" == "master" ]; then travis_terminate 0; fi
- if [ "$TRAVIS_BRANCH" == *"review"* ]; then travis_terminate 0; fi

stages:
  - name: Test
  - name: Deploy

jobs:
  include:
    - stage: "Test"
      name: "unit tests"
      script:
        - docker build -t cpp --build-arg PROJECT=$TRAVIS_BRANCH .
        - docker run -e TRAVIS_BUILD_NUMBER=$TRAVIS_BUILD_NUMBER cpp test
      if: |
        (type = push AND branch != editor)
    - stage: "Deploy"
      name: "deploy"
      script:
        - docker build -t cpp --build-arg PROJECT=$TRAVIS_BRANCH .
        - docker run -v $(pwd)/$TRAVIS_BRANCH:/app -e TRAVIS_BUILD_NUMBER=$TRAVIS_BUILD_NUMBER cpp deb
        - cd $TRAVIS_BRANCH && curl -T $TRAVIS_BRANCH-0.0.$TRAVIS_BUILD_NUMBER-Linux.deb -uf0m41h4u7:$BINTRAY_API_KEY "https://api.bintray.com/content/f0m41h4u7/cpp-hw/$TRAVIS_BRANCH/$TRAVIS_BUILD_NUMBER/$TRAVIS_BRANCH-0.0.$TRAVIS_BUILD_NUMBER-Linux.deb;deb_distribution=trusty;deb_component=main;deb_architecture=amd64;publish=1"
      deploy:
        provider: pages
        skip_cleanup: true
        github_token: $GITHUB_TOKEN
        keep_history: false
        local_dir: $TRAVIS_BRANCH/html
      if: |
        (type = push)
